### ISSUE TITLE
Makefile produces literal HTML

### ISSUE THREAD

**Issue by TheSystemGuy1337** [dreamscached/rickroll#5]
This is a showstopper problem. I have compiled this on Linux Mint (as I switched from the dumpster fire Windows 11) and tried compiling it. It passed, but the executable is not an executable at all: It's HTML source code from the YouTube page itself. This renders the makescript completely useless as all it does is copies HTML from the YouTube page verbatim instead of compiling into valid POSIX machine code.

UPDATE: The worse gets worse as both makefiles produce HTML output instead of machine code. This indicates that both makefiles are broken and should be removed or revamped.

**Comment by dreamscached** [comment]
Hi! Could you please provide an output from it, or your compilation steps, how you did that?

**Comment by TheSystemGuy1337** [comment]
I determined the fault: Linux Mint was actively tearing itself apart during compilation. I only realized the damage Linux Mint sustained after VLC quit on me and refused to start back up, and all my programs vanishing into the void. I rebooted and I ended up in good ol' TTY hell. After using Timeshift to fix the issue, I tried the process again and it worked and produced valid machine code.

**Comment by TheSystemGuy1337** [comment]
With this out of the way, a precompiled Linux binary is now available, and I will attach it here for you to add to releases.
[rickroll.zip](https://github.com/dreamscached/rickrollcxx/files/11644287/rickroll.zip)
